// Generated by CoffeeScript 1.6.3
(function() {
  window.BoardApp = (function() {
    var currentPlayer, lastBox, players, whoStart;

    function BoardApp(board_data) {
      var boardData;
      this.printBoard();
      boardData = board_data;
    }

    BoardApp.prototype.star = function() {
      players[currentPlayer].turn();
      return currentPlayer++;
    };

    BoardApp.prototype.nextTurn = function() {
      if (currentPlayer === players.length) {
        currentPlayer--;
      }
      return players[currentPlayer].turn();
    };

    whoStart = function() {
      return 0;
    };

    BoardApp.prototype.printBoard = function() {
      return this.printNumbers();
    };

    BoardApp.prototype.printNumbers = function() {
      var box, boxDiv, boxes, id, _i, _len, _results;
      boxes = $("#board td");
      _results = [];
      for (_i = 0, _len = boxes.length; _i < _len; _i++) {
        box = boxes[_i];
        id = box.id;
        id = parseInt(id.replace('box_', ''));
        boxDiv = "<div class=\"box\"> " + (id + 1) + " </div>";
        _results.push($(box).html(boxDiv));
      }
      return _results;
    };

    lastBox = boardData.length;

    players = [new Player('Player1', lastBox), new Player('Player2', lastBox)];

    currentPlayer = whoStart();

    return BoardApp;

  })();

}).call(this);
