// Generated by CoffeeScript 1.6.3
(function() {
  window.Dice = (function() {
    function Dice() {}

    Dice.prototype["throw"] = function() {
      return Math.floor(Math.random() * 6 + 1);
    };

    return Dice;

  })();

}).call(this);
