// Generated by CoffeeScript 1.6.3
(function() {
  window.boardApp = new BoardApp(boardData);

  $('#questionWrapper').on('click', '.answer', function(event) {
    event.preventDefault();
    alert($(this).data('valid'));
    return $(this).closest("#questionWrapper").html('');
  });

}).call(this);
